# Generated by Django 4.2.2 on 2023-06-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogame', '0002_platforms_alter_game_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(max_length=200),
        ),
    ]
