# Generated by Django 4.2.2 on 2023-06-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogame', '0005_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='master',
            field=models.BooleanField(default=False),
        ),
    ]
