# Generated by Django 4.2.2 on 2023-06-23 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elogame', '0006_game_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='duels',
            new_name='numberOfduels',
        ),
        migrations.CreateModel(
            name='duels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueltoken', models.CharField(max_length=100)),
                ('eloGame1', models.IntegerField()),
                ('eloGame2', models.IntegerField()),
                ('game1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game1', to='elogame.game')),
                ('game2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game2', to='elogame.game')),
            ],
        ),
    ]
