# Generated by Django 4.2.2 on 2023-06-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogame', '0007_rename_duels_game_numberofduels_duels'),
    ]

    operations = [
        migrations.AddField(
            model_name='duels',
            name='newEloGame1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='duels',
            name='newEloGame2',
            field=models.IntegerField(default=0),
        ),
    ]
