# Generated by Django 4.2.2 on 2023-06-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elogame', '0008_duels_newelogame1_duels_newelogame2'),
    ]

    operations = [
        migrations.AddField(
            model_name='duels',
            name='eloToUpdateGame1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='duels',
            name='eloToUpdateGame2',
            field=models.IntegerField(default=0),
        ),
    ]
